# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('done', models.BooleanField(default=False)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('pomodoros', models.IntegerField()),
            ],
        ),
    ]
